# Generated by Django 3.2.16 on 2024-07-10 23:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_recepcion', models.DateField(default=django.utils.timezone.now)),
                ('hora_recepcion', models.TimeField(default=django.utils.timezone.now)),
                ('entidad_emisora', models.CharField(max_length=100)),
                ('numero_cedula_expediente', models.CharField(max_length=50)),
                ('dirigido_a', models.CharField(max_length=100)),
                ('recepcionista', models.CharField(choices=[('Amanda González', 'Amanda González'), ('Wanda Pastor', 'Wanda Pastor')], max_length=100)),
                ('colaborador_entrega', models.CharField(choices=[('Usuario1', 'Usuario1'), ('Usuario2', 'Usuario2')], max_length=100)),
                ('fecha_hora_entrega', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
